DELETE FROM IMAGE;
DELETE FROM PRODUCT;
INSERT INTO PRODUCT(name, description) VALUES ('PRODUCT_FIND_ALL_1', 'PRODUCT_FIND_ALL_1');
INSERT INTO PRODUCT(name, description) VALUES ('PRODUCT_FIND_ALL_2', 'PRODUCT_FIND_ALL_2');
INSERT INTO PRODUCT(name, description) VALUES ('PRODUCT_FIND_ALL_3', 'PRODUCT_FIND_ALL_3');
INSERT INTO PRODUCT(name, description) VALUES ('PRODUCT_FIND_ALL_4', 'PRODUCT_FIND_ALL_4');
