INSERT INTO PRODUCT(name, description) VALUES ('Test Product Save Image', 'Produto Teste Save Image');
INSERT INTO PRODUCT(name, description) VALUES ('TEST_PRODUCT_UPDATE_IMAGE', 'TEST_PRODUCT_UPDATE_IMAGE');
INSERT INTO PRODUCT(name, description) VALUES ('TEST_DELETE_IMAGE', 'TEST_DELETE_IMAGE');
INSERT INTO PRODUCT(name, description) VALUES ('TEST_FINDBYID_IMAGE', 'TEST_FINDBYID_IMAGE');
